// <auto-generated />
using System;
using FraudRuleEngine.Evaluations.Worker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudRuleEngine.Evaluations.Worker.Data.Migrations
{
    [DbContext(typeof(RulesEngineDbContext))]
    [Migration("20251126222340_FraudCheckUpdateAddAccountId")]
    partial class FraudCheckUpdateAddAccountId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudRuleEngine.Evaluations.Worker.Data.Models.FraudCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FraudCheckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OverallRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FraudCheckId")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.HasIndex("AccountId", "EvaluatedAt")
                        .IsUnique();

                    b.ToTable("fraud_checks", (string)null);
                });

            modelBuilder.Entity("FraudRuleEngine.Evaluations.Worker.Data.Models.FraudRuleMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configuration");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RuleName")
                        .IsUnique();

                    b.ToTable("fraud_rules_metadata", (string)null);
                });

            modelBuilder.Entity("FraudRuleEngine.Evaluations.Worker.Data.Models.FraudCheck", b =>
                {
                    b.OwnsMany("FraudRuleEngine.Core.Domain.ValueObjects.FraudRuleResult", "RuleResults", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("FraudCheckId")
                                .HasColumnType("integer");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("RiskScore")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.Property<string>("RuleName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<bool>("Triggered")
                                .HasColumnType("boolean");

                            b1.HasKey("Id");

                            b1.HasIndex("FraudCheckId");

                            b1.ToTable("fraud_rule_results", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FraudCheckId");
                        });

                    b.Navigation("RuleResults");
                });
#pragma warning restore 612, 618
        }
    }
}
